# web > tasks > create_skel.yml
---

- name: make .ssh with permissions 0700
  file: path=/etc/skel/.ssh state=directory mode=0700

- name: make .ssh/authorized_keys with permissions 0644
  file: path=/etc/skel/.ssh/authorized_keys state=touch mode=0644

- name: make public_html with permissions 0755
  file: path=/etc/skel/public_html state=directory mode=0755

- name: make mail with permissions 0700
  file: path=/etc/skel/mail state=directory mode=0700
