# web > tasks > install_apache2.yml
---

- name: install apache2
  apt: name=apache2 state=present
  notify:
    - start apache2

- name: enabled userdir
  apache2_module: name=userdir state=present
  notify:
    - restart apache2
