# site.yml
---

- name: apply config to all nodes
  hosts: vagrant
  sudo: yes
  roles:
    - common


- name: install webserver
  hosts: vagrant
  sudo: yes
  roles: 
    - web

- name: install mailserver
  hosts: vagrant
  sudo: yes
  roles:
    - mail


