# site.yml
---

- name: set up the server generics
  hosts: all
  sudo: yes
  roles:
    - common

- name: install webserver
  hosts: all
  sudo: yes
  roles:
    - web

- name: install mailserver
  hosts: all
  sudo: yes
  roles:
    - mail
