# site.yml
---

- name: apply config to all nodes
  hosts: all
  # sudo: yes
  roles:
    - common

- name: install webserver
  hosts: all
  # sudo: yes
  roles: 
    - web

- name: install mailserver
  hosts: all
  # sudo: yes
  roles:
    - mail
